# Setup
setup: simclr

# Model
backbone: resnet18
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: birds-200-2011
val_db_name: birds-200-2011
num_classes: 200
db_targets: attributes
num_attribute_classes: 10

# Loss
criterion: attributes-fine-tune
criterion_kwargs:
   temperature: 0.1 

# Hyperparameters
epochs: 500
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.4
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 192 # 256 #512
num_workers: 2 # 8

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 48 # 32
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.48551162, 0.4966364, 0.42870739] # <- 32x32, 64z64 -> [0.48547093, 0.49658954, 0.42867865]
      std: [0.21338888,0.20869549,0.24722904] #  <- 32x32, 64z64 -> [0.22167043, 0.21696173, 0.25494133]

transformation_kwargs:
   crop_size: 48 # 32
   normalize:
      mean: [0.48551162, 0.4966364, 0.42870739] # <- 32x32, 64z64 -> [0.48547093, 0.49658954, 0.42867865]
      std: [0.21338888,0.20869549,0.24722904] #  <- 32x32, 64z64 -> [0.22167043, 0.21696173, 0.25494133]
