# Setup
setup: simclr

# Model
backbone: resnet18
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: celeb-a
val_db_name: celeb-a
num_classes: 10177
db_targets: attr
attr_index: 20
num_attribute_classes: 2  # e.g. Male/Female

# Loss
criterion: attributes-fine-tune
criterion_kwargs:
   temperature: 0.1 

# Hyperparameters
epochs: 500
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.1
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 192 # 256 #512
num_workers: 2 # 8

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 48 # 32
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.50773493, 0.42190761, 0.37649541]
      std: [0.30310455, 0.28182062, 0.28093909]

transformation_kwargs:
   crop_size: 48 # 32
   normalize:
      mean: [0.50773493, 0.42190761, 0.37649541]
      std: [0.30310455, 0.28182062, 0.28093909]
